
tasks:
  - init: pip install -r requirements.txt
    command: python main.py



vscode:
  extensions:
    - alexcvzz.vscode-sqlite
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - mtxr.sqltools-driver-sqlite
    - mtxr.sqltools
